// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyhdksaptmcnwlypnmqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5aGRrc2FwdG1jbndseXBubXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTI2NzgsImV4cCI6MjA2NTU2ODY3OH0.t1hzeBmW8qri7U4df9wyfTVW1U2GmjDo564mNFCLc4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);